Shooter
zense/Canvas-Competition pull request #12
Opened 2019-09-10 16:55 UTC by Sahaj8

2019-09-10 17:25 UTC, satu0king requested changes
Try and learn how to work with branches. Then you wouldn't need to delete index.html and create shoot.html
Also your PR should have just 1-2 commits after master.

2019-09-11 02:22 UTC, Kartik-Sama commented
While deceasing velocity shouldn't speed approach 0, instead of again increasing in negative direction ?

2019-09-11 06:42 UTC, satu0king requested changes
I think there is a mistake in the PR, I cannot see the shooter code .. Maybe create a new PR ?

2019-09-11 06:42 UTC, satu0king commented on canvas.js
> -    console.log("Dummy KeyDownCallback - Override canvas.KeyDownCallback");
Why is there a change here??

2019-09-11 07:46 UTC, Sahaj8 commented on canvas.js
> -    console.log("Dummy KeyDownCallback - Override canvas.KeyDownCallback");
I will change it and send a new pr.

2019-10-19 18:23 UTC, satu0king commented
@Sahaj8 should we close this PR?

2019-10-19 20:13 UTC, closed without merging