examples/Game-TrafficRush
zense/Canvas-Competition pull request #18
Opened 2019-09-17 10:52 UTC by Kartik-Sama

This is a simple game in which you need to avoid obstacles as you move on.

2019-10-19 18:21 UTC, satu0king commented
Very Impressive

2019-10-19 18:22 UTC, satu0king requested changes

2019-10-19 18:22 UTC, satu0king commented on index.html
> +    function globalInitialize()
There is `canvas.setup()` exactly for this, please use that. We can merge once that change is done.

2019-11-05 11:10 UTC, Kartik-Sama commented on index.html
> +    function globalInitialize()
Please can you clarify whether you are expecting changes to be made in canvas.setup in canvas.js. Are we allowed to alter canvas.js ?
Or is it something else you are expecting.

2019-11-14 02:01 UTC, Kartik-Sama commented
I have overwritten canvas.setupFunction as you have suggested.

2021-03-21 11:18 UTC, closed without merging